// <auto-generated />
using System;
using LaForetMagique.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaForetMagique.Migrations
{
    [DbContext(typeof(LaforetMagiqueDbContext))]
    [Migration("20260403144011_first_migration")]
    partial class first_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaForetMagique.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("x")
                        .HasColumnType("int");

                    b.Property<int>("y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("x", "y");

                    b.ToTable("Entities");

                    b.HasDiscriminator<string>("EntityType").HasValue("Entity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LaForetMagique.Models.Creature", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Entity");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasDiscriminator().HasValue("Creature");
                });

            modelBuilder.Entity("LaForetMagique.Models.Item", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Entity");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Entities", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Item_Name");
                        });

                    b.HasDiscriminator().HasValue("Item");
                });

            modelBuilder.Entity("LaForetMagique.Models.Bug", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Creature");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<bool>("IsHostile")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Bug");
                });

            modelBuilder.Entity("LaForetMagique.Models.Schtroumpf", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Creature");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Schtroumpf");
                });

            modelBuilder.Entity("LaForetMagique.Models.Berry", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Item");

                    b.Property<int>("HealAmount")
                        .HasColumnType("int");

                    b.ToTable("Entities", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Item_Name");

                            t.Property("HealAmount")
                                .HasColumnName("Berry_HealAmount");
                        });

                    b.HasDiscriminator().HasValue("Berry");
                });

            modelBuilder.Entity("LaForetMagique.Models.BluePotion", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Item");

                    b.Property<int>("HealAmount")
                        .HasColumnType("int");

                    b.ToTable("Entities", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Item_Name");
                        });

                    b.HasDiscriminator().HasValue("BluePotion");
                });

            modelBuilder.Entity("LaForetMagique.Models.RedPotion", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Item");

                    b.Property<int>("HealAmount")
                        .HasColumnType("int");

                    b.ToTable("Entities", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Item_Name");

                            t.Property("HealAmount")
                                .HasColumnName("RedPotion_HealAmount");
                        });

                    b.HasDiscriminator().HasValue("RedPotion");
                });

            modelBuilder.Entity("LaForetMagique.Models.Bzzfly", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Bug");

                    b.Property<int>("FlightSpeed")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BzzFly");
                });

            modelBuilder.Entity("LaForetMagique.Models.Spider", b =>
                {
                    b.HasBaseType("LaForetMagique.Models.Bug");

                    b.Property<int>("WebStrength")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Spider");
                });
#pragma warning restore 612, 618
        }
    }
}
